# sp:
    # fastqc/data:
      # fn: "fastqc_data.txt"
    # fastqc/zip:
      # fn: "*_fastqc.zip"
module_order:
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      target: ""
      path_filters:
        - "*fastp_fastqc.zip"
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      path_filters:
        - "*1_fastqc.zip"
plots_force_interactive: true
